/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.integratesys.view;

import br.unesp.rc.integratesys.ambiente.Parametros;
import javax.swing.JOptionPane;

/**
 *
 * @author Waldeilson
 */
public class FormParametros extends FormBase {

    private final Parametros parametros;

    public FormParametros() {
        initComponents();
        definirImagemSensores();
        parametros = new Parametros();
        getParametros();
    }

    private void definirImagemSensores() {
        lblSensorTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/temperatura.png")));
        lblSensorUmidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/umidade.png")));
        lblSensorLuminosidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/luminosidade.png")));
    }

    private void getParametros() {
        txtTemperaturaIdeal.setText(String.valueOf(parametros.getTemperaturaIdeal()));
        txtTemperaturaMaxima.setText(String.valueOf(parametros.getTemperaturaMaximaCritica()));
        txtTemperaturaMinima.setText(String.valueOf(parametros.getTemperaturaMinimaCritica()));
        txtUmidadeIdeal.setText(String.valueOf(parametros.getUmidadeIdeal()));
        txtUmidadeMaxima.setText(String.valueOf(parametros.getUmidadeMaximaCritica()));
        txtUmidadeMinima.setText(String.valueOf(parametros.getUmidadeMinimaCritica()));
        txtLuminosidadeIdeal.setText(String.valueOf(parametros.getLuminosidadeIdeal()));
        txtLuminosidadeMaxima.setText(String.valueOf(parametros.getLuminosidadeMaximaCritica()));
        txtLuminosidadeMinima.setText(String.valueOf(parametros.getLuminosidadeMinimaCritica()));
    }

    private void setParametros() {
        parametros.setTemperaturaIdeal(Integer.parseInt(txtTemperaturaIdeal.getText()));
        parametros.setTemperaturaMaximaCritica(Integer.parseInt(txtTemperaturaMaxima.getText()));
        parametros.setTemperaturaMinimaCritica(Integer.parseInt(txtTemperaturaMinima.getText()));
        parametros.setUmidadeIdeal(Integer.parseInt(txtUmidadeIdeal.getText()));
        parametros.setUmidadeMaximaCritica(Integer.parseInt(txtUmidadeMaxima.getText()));
        parametros.setUmidadeMinimaCritica(Integer.parseInt(txtUmidadeMinima.getText()));
        parametros.setLuminosidadeIdeal(Integer.parseInt(txtLuminosidadeIdeal.getText()));
        parametros.setLuminosidadeMaximaCritica(Integer.parseInt(txtLuminosidadeMaxima.getText()));
        parametros.setLuminosidadeMinimaCritica(Integer.parseInt(txtLuminosidadeMinima.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        pnlParametros = new javax.swing.JPanel();
        pnlSensorTemperatura = new javax.swing.JPanel();
        lblSensorTemperatura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTemperaturaIdeal = new javax.swing.JTextField();
        txtTemperaturaMinima = new javax.swing.JTextField();
        txtTemperaturaMaxima = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlSensorLuminosidade = new javax.swing.JPanel();
        lblSensorLuminosidade = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLuminosidadeIdeal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLuminosidadeMinima = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLuminosidadeMaxima = new javax.swing.JTextField();
        pnlSensorUmidade = new javax.swing.JPanel();
        lblSensorUmidade = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUmidadeIdeal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUmidadeMinima = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUmidadeMaxima = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IntegrateSys v1.0");

        btnSalvar.setText("OK");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        pnlParametros.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));
        pnlParametros.setName(""); // NOI18N

        pnlSensorTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura"));

        lblSensorTemperatura.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorTemperatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorTemperatura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("Temperatura ideal");

        txtTemperaturaIdeal.setColumns(5);
        txtTemperaturaIdeal.setText("jTextField1");

        txtTemperaturaMinima.setColumns(5);
        txtTemperaturaMinima.setText("jTextField2");

        txtTemperaturaMaxima.setColumns(5);
        txtTemperaturaMaxima.setText("jTextField3");

        jLabel2.setText("Temperatura Máxima");

        jLabel3.setText("Temperatura Mínima");

        javax.swing.GroupLayout pnlSensorTemperaturaLayout = new javax.swing.GroupLayout(pnlSensorTemperatura);
        pnlSensorTemperatura.setLayout(pnlSensorTemperaturaLayout);
        pnlSensorTemperaturaLayout.setHorizontalGroup(
            pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(txtTemperaturaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTemperaturaIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorTemperaturaLayout.setVerticalGroup(
            pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                .addComponent(lblSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(txtTemperaturaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pnlSensorLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Luminosidade"));

        lblSensorLuminosidade.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorLuminosidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorLuminosidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setText("Luminosidade ideal");

        txtLuminosidadeIdeal.setColumns(5);
        txtLuminosidadeIdeal.setText("jTextField1");

        jLabel8.setText("Luminosidade Mínima");

        txtLuminosidadeMinima.setColumns(5);
        txtLuminosidadeMinima.setText("jTextField2");

        jLabel9.setText("Luminosidade Máxima");

        txtLuminosidadeMaxima.setColumns(5);
        txtLuminosidadeMaxima.setText("jTextField3");

        javax.swing.GroupLayout pnlSensorLuminosidadeLayout = new javax.swing.GroupLayout(pnlSensorLuminosidade);
        pnlSensorLuminosidade.setLayout(pnlSensorLuminosidadeLayout);
        pnlSensorLuminosidadeLayout.setHorizontalGroup(
            pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(txtLuminosidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtLuminosidadeIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuminosidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorLuminosidadeLayout.setVerticalGroup(
            pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                .addComponent(lblSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLuminosidadeIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(txtLuminosidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLuminosidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSensorUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Umidade"));

        lblSensorUmidade.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorUmidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorUmidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setText("Umidade ideal");

        txtUmidadeIdeal.setColumns(5);
        txtUmidadeIdeal.setText("jTextField1");

        jLabel5.setText("Umidade Mínima");

        txtUmidadeMinima.setColumns(5);
        txtUmidadeMinima.setText("jTextField2");

        jLabel6.setText("Umidade Máxima");

        txtUmidadeMaxima.setColumns(5);
        txtUmidadeMaxima.setText("jTextField3");

        javax.swing.GroupLayout pnlSensorUmidadeLayout = new javax.swing.GroupLayout(pnlSensorUmidade);
        pnlSensorUmidade.setLayout(pnlSensorUmidadeLayout);
        pnlSensorUmidadeLayout.setHorizontalGroup(
            pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtUmidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtUmidadeIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUmidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorUmidadeLayout.setVerticalGroup(
            pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                .addComponent(lblSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUmidadeIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(txtUmidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUmidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlParametrosLayout = new javax.swing.GroupLayout(pnlParametros);
        pnlParametros.setLayout(pnlParametrosLayout);
        pnlParametrosLayout.setHorizontalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                .addComponent(pnlSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlParametrosLayout.setVerticalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSensorTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSensorUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSensorLuminosidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addComponent(pnlParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnSalvar.getAccessibleContext().setAccessibleName("Salvar");
        pnlParametros.getAccessibleContext().setAccessibleName("Parametros");
        pnlParametros.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        setParametros();
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblSensorLuminosidade;
    private javax.swing.JLabel lblSensorTemperatura;
    private javax.swing.JLabel lblSensorUmidade;
    private javax.swing.JPanel pnlParametros;
    private javax.swing.JPanel pnlSensorLuminosidade;
    private javax.swing.JPanel pnlSensorTemperatura;
    private javax.swing.JPanel pnlSensorUmidade;
    private javax.swing.JTextField txtLuminosidadeIdeal;
    private javax.swing.JTextField txtLuminosidadeMaxima;
    private javax.swing.JTextField txtLuminosidadeMinima;
    private javax.swing.JTextField txtTemperaturaIdeal;
    private javax.swing.JTextField txtTemperaturaMaxima;
    private javax.swing.JTextField txtTemperaturaMinima;
    private javax.swing.JTextField txtUmidadeIdeal;
    private javax.swing.JTextField txtUmidadeMaxima;
    private javax.swing.JTextField txtUmidadeMinima;
    // End of variables declaration//GEN-END:variables

}
