/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.integratesys.view;

import br.unesp.rc.integratesys.ambiente.Ambiente;
import br.unesp.rc.integratesys.ambiente.Parametros;
import br.unesp.rc.integratesys.atuadores.Nivel;
import br.unesp.rc.integratesys.utils.CondicaoTempo;
import br.unesp.rc.integratesys.utils.Tarefa;
import java.awt.Component;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Helton
 */
public class FormParametros extends FormBase {

    private final Parametros parametros;

    public FormParametros() {
        initComponents();
        definirImagemSensores();
        definirImagemAtuadores();
        parametros = new Parametros();
        getParametros();
    }

    private void definirImagemSensores() {
        lblSensorTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/temperatura.png")));
        lblSensorUmidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/umidade.png")));
        lblSensorLuminosidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/luminosidade.png")));
    }

    private void definirImagemAtuadores() {
        lblVentilador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/ventilador.png")));
        lblAquecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/aquecedor.png")));
        lblUmidificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/umidificador.png")));
        lblLampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/lampada.png")));

    }
    
    private void getParametros(){
        txtTemperaturaIdeal.setText(String.valueOf(parametros.getTemperaturaIdeal()));
        txtTemperaturaMaxima.setText(String.valueOf(parametros.getTemperaturaMaximaCritica()));
        txtTemperaturaMinima.setText(String.valueOf(parametros.getTemperaturaMinimaCritica()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtabParametros = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        txtTemperaturaIdeal = new javax.swing.JTextField();
        txtTemperaturaMinima = new javax.swing.JTextField();
        txtTemperaturaMaxima = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sepAtuadores = new javax.swing.JSeparator();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IntegrateSys v1.0");

        jtabParametros.setName(""); // NOI18N

        pnlControleTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Temperatura"));
        pnlControleTemperatura.setName(""); // NOI18N

        pnlSensorTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor"));

        lblSensorTemperatura.setText("sensor de temperatura");
        lblSensorTemperatura.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorTemperatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorTemperatura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("Temperatura ideal");

        txtTemperaturaIdeal.setColumns(5);
        txtTemperaturaIdeal.setText("jTextField1");

        txtTemperaturaMinima.setColumns(5);
        txtTemperaturaMinima.setText("jTextField2");

        txtTemperaturaMaxima.setColumns(5);
        txtTemperaturaMaxima.setText("jTextField3");

        jLabel2.setText("Temperatura Máxima");

        jLabel3.setText("Temperatura Mínima");

        javax.swing.GroupLayout pnlSensorTemperaturaLayout = new javax.swing.GroupLayout(pnlSensorTemperatura);
        pnlSensorTemperatura.setLayout(pnlSensorTemperaturaLayout);
        pnlSensorTemperaturaLayout.setHorizontalGroup(
            pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(txtTemperaturaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTemperaturaIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorTemperaturaLayout.setVerticalGroup(
            pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                .addComponent(lblSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(txtTemperaturaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pnlAtuadoresTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Atuadores"));

        lblVentilador.setText("ventilador");
        lblVentilador.setBorder(new javax.swing.border.MatteBorder(null));
        lblVentilador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVentilador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblAquecedor.setText("aquecedor");
        lblAquecedor.setBorder(new javax.swing.border.MatteBorder(null));
        lblAquecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAquecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        sepAtuadores.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnlAtuadoresTemperaturaLayout = new javax.swing.GroupLayout(pnlAtuadoresTemperatura);
        pnlAtuadoresTemperatura.setLayout(pnlAtuadoresTemperaturaLayout);
        pnlAtuadoresTemperaturaLayout.setHorizontalGroup(
            pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadoresTemperaturaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblVentilador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(sepAtuadores, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblAquecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnlAtuadoresTemperaturaLayout.setVerticalGroup(
            pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadoresTemperaturaLayout.createSequentialGroup()
                .addGroup(pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAquecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVentilador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlAtuadoresTemperaturaLayout.createSequentialGroup()
                .addComponent(sepAtuadores)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlControleTemperaturaLayout = new javax.swing.GroupLayout(pnlControleTemperatura);
        pnlControleTemperatura.setLayout(pnlControleTemperaturaLayout);
        pnlControleTemperaturaLayout.setHorizontalGroup(
            pnlControleTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleTemperaturaLayout.createSequentialGroup()
                .addComponent(pnlSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtuadoresTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlControleTemperaturaLayout.setVerticalGroup(
            pnlControleTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAtuadoresTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSensorTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtabParametros.addTab("Temperatura", pnlControleTemperatura);
        pnlControleTemperatura.getAccessibleContext().setAccessibleDescription("");

        pnlControleUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Umidade"));

        pnlSensorUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor"));

        lblSensorUmidade.setText("sensor de umidade");
        lblSensorUmidade.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorUmidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorUmidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlSensorUmidadeLayout = new javax.swing.GroupLayout(pnlSensorUmidade);
        pnlSensorUmidade.setLayout(pnlSensorUmidadeLayout);
        pnlSensorUmidadeLayout.setHorizontalGroup(
            pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorUmidadeLayout.setVerticalGroup(
            pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                .addComponent(lblSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pnlAtuadorUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atuador"));

        lblUmidificador.setText("umidificador");
        lblUmidificador.setBorder(new javax.swing.border.MatteBorder(null));
        lblUmidificador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUmidificador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlAtuadorUmidadeLayout = new javax.swing.GroupLayout(pnlAtuadorUmidade);
        pnlAtuadorUmidade.setLayout(pnlAtuadorUmidadeLayout);
        pnlAtuadorUmidadeLayout.setHorizontalGroup(
            pnlAtuadorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtuadorUmidadeLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblUmidificador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlAtuadorUmidadeLayout.setVerticalGroup(
            pnlAtuadorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadorUmidadeLayout.createSequentialGroup()
                .addComponent(lblUmidificador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlControleUmidadeLayout = new javax.swing.GroupLayout(pnlControleUmidade);
        pnlControleUmidade.setLayout(pnlControleUmidadeLayout);
        pnlControleUmidadeLayout.setHorizontalGroup(
            pnlControleUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleUmidadeLayout.createSequentialGroup()
                .addComponent(pnlSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtuadorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControleUmidadeLayout.setVerticalGroup(
            pnlControleUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControleUmidadeLayout.createSequentialGroup()
                .addGroup(pnlControleUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSensorUmidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAtuadorUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtabParametros.addTab("Umidade", pnlControleUmidade);

        pnlControleLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Luminosidade"));

        pnlSensorLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor"));

        lblSensorLuminosidade.setText("sensor de luminosidade");
        lblSensorLuminosidade.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorLuminosidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorLuminosidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlSensorLuminosidadeLayout = new javax.swing.GroupLayout(pnlSensorLuminosidade);
        pnlSensorLuminosidade.setLayout(pnlSensorLuminosidadeLayout);
        pnlSensorLuminosidadeLayout.setHorizontalGroup(
            pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorLuminosidadeLayout.setVerticalGroup(
            pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                .addComponent(lblSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAtuadorLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atuador"));

        lblLampada.setText("lâmpada");
        lblLampada.setBorder(new javax.swing.border.MatteBorder(null));
        lblLampada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLampada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlAtuadorLuminosidadeLayout = new javax.swing.GroupLayout(pnlAtuadorLuminosidade);
        pnlAtuadorLuminosidade.setLayout(pnlAtuadorLuminosidadeLayout);
        pnlAtuadorLuminosidadeLayout.setHorizontalGroup(
            pnlAtuadorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtuadorLuminosidadeLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lblLampada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlAtuadorLuminosidadeLayout.setVerticalGroup(
            pnlAtuadorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadorLuminosidadeLayout.createSequentialGroup()
                .addComponent(lblLampada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlControleLuminosidadeLayout = new javax.swing.GroupLayout(pnlControleLuminosidade);
        pnlControleLuminosidade.setLayout(pnlControleLuminosidadeLayout);
        pnlControleLuminosidadeLayout.setHorizontalGroup(
            pnlControleLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleLuminosidadeLayout.createSequentialGroup()
                .addComponent(pnlSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtuadorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlControleLuminosidadeLayout.setVerticalGroup(
            pnlControleLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleLuminosidadeLayout.createSequentialGroup()
                .addGroup(pnlControleLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAtuadorLuminosidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSensorLuminosidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtabParametros.addTab("Luminosidade", pnlControleLuminosidade);

        btnSalvar.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addComponent(jtabParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtabParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jtabParametros.getAccessibleContext().setAccessibleName("tabParametros");
        jtabParametros.getAccessibleContext().setAccessibleDescription("");
        btnSalvar.getAccessibleContext().setAccessibleName("Salvar");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jtabParametros;
    private final javax.swing.JLabel lblAquecedor = new javax.swing.JLabel();
    private final javax.swing.JLabel lblLampada = new javax.swing.JLabel();
    private final javax.swing.JLabel lblSensorLuminosidade = new javax.swing.JLabel();
    private final javax.swing.JLabel lblSensorTemperatura = new javax.swing.JLabel();
    private final javax.swing.JLabel lblSensorUmidade = new javax.swing.JLabel();
    private final javax.swing.JLabel lblUmidificador = new javax.swing.JLabel();
    private final javax.swing.JLabel lblVentilador = new javax.swing.JLabel();
    private final javax.swing.JPanel pnlAtuadorLuminosidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlAtuadorUmidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlAtuadoresTemperatura = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlControleLuminosidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlControleTemperatura = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlControleUmidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlSensorLuminosidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlSensorTemperatura = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlSensorUmidade = new javax.swing.JPanel();
    private javax.swing.JSeparator sepAtuadores;
    private javax.swing.JTextField txtTemperaturaIdeal;
    private javax.swing.JTextField txtTemperaturaMaxima;
    private javax.swing.JTextField txtTemperaturaMinima;
    // End of variables declaration//GEN-END:variables

}
