/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unesp.rc.integratesys.view;

import br.unesp.rc.integratesys.ambiente.Ambiente;
import br.unesp.rc.integratesys.utils.Tarefa;
import br.unesp.rc.integratesys.utils.Varredor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Helton
 */
public class FormAmbiente extends FormBase {

    private final Ambiente ambiente;
    private final Varredor varredor;
    
    /**
     * Creates new form FormPrincipal
     */
    public FormAmbiente() {
        initComponents();        
        ambiente = new Ambiente();
        varredor = new Varredor(ambiente.getAgendadorTarefas(), new Tarefa() {
            
            private void verificarSituacaoCritica() {
                //tratar!
            }
            
            private void definirImagemSensores() {
               lblSensorTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/temperatura.png")));
               lblSensorUmidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/umidade.png")));
               lblSensorLuminosidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sensores/luminosidade.png")));
            }
            
            private void definirImagemAtuadores() {
                lblVentilador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/ventilador.png")));
                lblLampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/lampada.png")));        
                lblUmidificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/umidificador.png")));        
                lblAquecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atuadores/aquecedor.png")));                
            }
            
            @Override
            public void executar() {
               lblTemperatura.setText(ambiente.getSensores().getSensorTemperatura().getTemperatura() + " ºC");
               lblUmidade.setText(ambiente.getSensores().getSensorUmidade().getUmidade() + " %");
               lblLuminosidade.setText(ambiente.getSensores().getSensorLuminosidade().getLuminosidade() + " %");
               definirImagemSensores();
               definirImagemAtuadores();
               verificarSituacaoCritica();
            }            
        });        
        ActionListener setLigadoDesligado = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                JToggleButton button = (JToggleButton)actionEvent.getSource();
                if (button.isSelected()) {
                    button.setText("Desligar");
                }
                else {
                    button.setText("Ligar");            
                }
            }            
        };
        tbtnInterruptorAquecedor.addActionListener(setLigadoDesligado);
        tbtnInterruptorLampada.addActionListener(setLigadoDesligado);
        tbtnInterruptorUmidificador.addActionListener(setLigadoDesligado);
        tbtnInterruptorVentilador.addActionListener(setLigadoDesligado);
        varredor.iniciar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtuadoresTemperatura = new javax.swing.JPanel();
        lblVentilador = new javax.swing.JLabel();
        lblAquecedor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IntegrateSys v1.0");

        pnlControleTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Temperatura"));

        pnlSensorTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor"));

        lblSensorTemperatura.setText("sensor de temperatura");
        lblSensorTemperatura.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorTemperatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorTemperatura.setPreferredSize(new java.awt.Dimension(128, 18));
        lblSensorTemperatura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblTemperatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTemperatura.setText("0º C");

        javax.swing.GroupLayout pnlSensorTemperaturaLayout = new javax.swing.GroupLayout(pnlSensorTemperatura);
        pnlSensorTemperatura.setLayout(pnlSensorTemperaturaLayout);
        pnlSensorTemperaturaLayout.setHorizontalGroup(
            pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                .addGroup(pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblTemperatura)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorTemperaturaLayout.setVerticalGroup(
            pnlSensorTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorTemperaturaLayout.createSequentialGroup()
                .addComponent(lblSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTemperatura)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnlAtuadoresTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Atuadores"));

        lblVentilador.setText("ventilador");
        lblVentilador.setBorder(new javax.swing.border.MatteBorder(null));
        lblVentilador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVentilador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblAquecedor.setText("aquecedor");
        lblAquecedor.setBorder(new javax.swing.border.MatteBorder(null));
        lblAquecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAquecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tbtnInterruptorAquecedor.setText("Ligar");
        tbtnInterruptorAquecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnInterruptorAquecedorActionPerformed(evt);
            }
        });

        tbtnInterruptorVentilador.setText("Ligar");
        tbtnInterruptorVentilador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnInterruptorVentiladorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAtuadoresTemperaturaLayout = new javax.swing.GroupLayout(pnlAtuadoresTemperatura);
        pnlAtuadoresTemperatura.setLayout(pnlAtuadoresTemperaturaLayout);
        pnlAtuadoresTemperaturaLayout.setHorizontalGroup(
            pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadoresTemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentilador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAquecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAtuadoresTemperaturaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tbtnInterruptorVentilador, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnInterruptorAquecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnlAtuadoresTemperaturaLayout.setVerticalGroup(
            pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadoresTemperaturaLayout.createSequentialGroup()
                .addGroup(pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAquecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVentilador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtuadoresTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtnInterruptorAquecedor)
                    .addComponent(tbtnInterruptorVentilador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlControleTemperaturaLayout = new javax.swing.GroupLayout(pnlControleTemperatura);
        pnlControleTemperatura.setLayout(pnlControleTemperaturaLayout);
        pnlControleTemperaturaLayout.setHorizontalGroup(
            pnlControleTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleTemperaturaLayout.createSequentialGroup()
                .addComponent(pnlSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtuadoresTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlControleTemperaturaLayout.setVerticalGroup(
            pnlControleTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSensorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlAtuadoresTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlControleLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Luminosidade"));

        pnlSensorLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor"));

        lblSensorLuminosidade.setText("sensor de luminosidade");
        lblSensorLuminosidade.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorLuminosidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorLuminosidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblLuminosidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLuminosidade.setText("0%");

        javax.swing.GroupLayout pnlSensorLuminosidadeLayout = new javax.swing.GroupLayout(pnlSensorLuminosidade);
        pnlSensorLuminosidade.setLayout(pnlSensorLuminosidadeLayout);
        pnlSensorLuminosidadeLayout.setHorizontalGroup(
            pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                .addGroup(pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblLuminosidade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorLuminosidadeLayout.setVerticalGroup(
            pnlSensorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorLuminosidadeLayout.createSequentialGroup()
                .addComponent(lblSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblLuminosidade)
                .addContainerGap())
        );

        pnlAtuadorLuminosidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atuador"));

        lblLampada.setText("lâmpada");
        lblLampada.setBorder(new javax.swing.border.MatteBorder(null));
        lblLampada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLampada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tbtnInterruptorLampada.setText("Ligar");
        tbtnInterruptorLampada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnInterruptorLampadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAtuadorLuminosidadeLayout = new javax.swing.GroupLayout(pnlAtuadorLuminosidade);
        pnlAtuadorLuminosidade.setLayout(pnlAtuadorLuminosidadeLayout);
        pnlAtuadorLuminosidadeLayout.setHorizontalGroup(
            pnlAtuadorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadorLuminosidadeLayout.createSequentialGroup()
                .addGroup(pnlAtuadorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAtuadorLuminosidadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLampada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAtuadorLuminosidadeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tbtnInterruptorLampada, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAtuadorLuminosidadeLayout.setVerticalGroup(
            pnlAtuadorLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadorLuminosidadeLayout.createSequentialGroup()
                .addComponent(lblLampada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnInterruptorLampada)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlControleLuminosidadeLayout = new javax.swing.GroupLayout(pnlControleLuminosidade);
        pnlControleLuminosidade.setLayout(pnlControleLuminosidadeLayout);
        pnlControleLuminosidadeLayout.setHorizontalGroup(
            pnlControleLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleLuminosidadeLayout.createSequentialGroup()
                .addComponent(pnlSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtuadorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlControleLuminosidadeLayout.setVerticalGroup(
            pnlControleLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleLuminosidadeLayout.createSequentialGroup()
                .addGroup(pnlControleLuminosidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAtuadorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlControleLuminosidadeLayout.createSequentialGroup()
                        .addComponent(pnlSensorLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlControleUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Umidade"));

        pnlSensorUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor"));

        lblSensorUmidade.setText("sensor de umidade");
        lblSensorUmidade.setBorder(new javax.swing.border.MatteBorder(null));
        lblSensorUmidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSensorUmidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblUmidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUmidade.setText("0%");

        javax.swing.GroupLayout pnlSensorUmidadeLayout = new javax.swing.GroupLayout(pnlSensorUmidade);
        pnlSensorUmidade.setLayout(pnlSensorUmidadeLayout);
        pnlSensorUmidadeLayout.setHorizontalGroup(
            pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                .addGroup(pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblUmidade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSensorUmidadeLayout.setVerticalGroup(
            pnlSensorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSensorUmidadeLayout.createSequentialGroup()
                .addComponent(lblSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUmidade)
                .addContainerGap())
        );

        pnlAtuadorUmidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atuador"));

        lblUmidificador.setText("umidificador");
        lblUmidificador.setBorder(new javax.swing.border.MatteBorder(null));
        lblUmidificador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUmidificador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tbtnInterruptorUmidificador.setText("Ligar");
        tbtnInterruptorUmidificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnInterruptorUmidificadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAtuadorUmidadeLayout = new javax.swing.GroupLayout(pnlAtuadorUmidade);
        pnlAtuadorUmidade.setLayout(pnlAtuadorUmidadeLayout);
        pnlAtuadorUmidadeLayout.setHorizontalGroup(
            pnlAtuadorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadorUmidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUmidificador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtuadorUmidadeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnInterruptorUmidificador, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlAtuadorUmidadeLayout.setVerticalGroup(
            pnlAtuadorUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtuadorUmidadeLayout.createSequentialGroup()
                .addComponent(lblUmidificador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnInterruptorUmidificador))
        );

        javax.swing.GroupLayout pnlControleUmidadeLayout = new javax.swing.GroupLayout(pnlControleUmidade);
        pnlControleUmidade.setLayout(pnlControleUmidadeLayout);
        pnlControleUmidadeLayout.setHorizontalGroup(
            pnlControleUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleUmidadeLayout.createSequentialGroup()
                .addComponent(pnlSensorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtuadorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlControleUmidadeLayout.setVerticalGroup(
            pnlControleUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSensorUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlControleUmidadeLayout.createSequentialGroup()
                .addComponent(pnlAtuadorUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de simulação"));

        tbtnIniciarSimulacao.setSelected(true);
        tbtnIniciarSimulacao.setText("Pausar simulação");
        tbtnIniciarSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnIniciarSimulacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtnIniciarSimulacao)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(tbtnIniciarSimulacao)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlControleUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlControleLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlControleTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlControleUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControleLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlControleTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlControleTemperatura.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnIniciarSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnIniciarSimulacaoActionPerformed
        if (tbtnIniciarSimulacao.isSelected()) {
            varredor.iniciar();
            tbtnIniciarSimulacao.setText("Pausar simulação");
        }
        else {
            varredor.pausar();
            tbtnIniciarSimulacao.setText("Iniciar simulação");
        }
    }//GEN-LAST:event_tbtnIniciarSimulacaoActionPerformed

    private void tbtnInterruptorVentiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnInterruptorVentiladorActionPerformed
        ambiente.getAtuadores().getVentilador().setLigado(tbtnInterruptorVentilador.isSelected());                
    }//GEN-LAST:event_tbtnInterruptorVentiladorActionPerformed

    private void tbtnInterruptorAquecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnInterruptorAquecedorActionPerformed
        ambiente.getAtuadores().getAquecedor().setLigado(tbtnInterruptorAquecedor.isSelected());
    }//GEN-LAST:event_tbtnInterruptorAquecedorActionPerformed

    private void tbtnInterruptorUmidificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnInterruptorUmidificadorActionPerformed
        ambiente.getAtuadores().getUmidificador().setLigado(tbtnInterruptorUmidificador.isSelected());
    }//GEN-LAST:event_tbtnInterruptorUmidificadorActionPerformed

    private void tbtnInterruptorLampadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnInterruptorLampadaActionPerformed
        ambiente.getAtuadores().getLampada().setLigado(tbtnInterruptorLampada.isSelected());
    }//GEN-LAST:event_tbtnInterruptorLampadaActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormAmbiente().exibir();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAquecedor;
    private final javax.swing.JLabel lblLampada = new javax.swing.JLabel();
    private final javax.swing.JLabel lblLuminosidade = new javax.swing.JLabel();
    private final javax.swing.JLabel lblSensorLuminosidade = new javax.swing.JLabel();
    private final javax.swing.JLabel lblSensorTemperatura = new javax.swing.JLabel();
    private final javax.swing.JLabel lblSensorUmidade = new javax.swing.JLabel();
    private final javax.swing.JLabel lblTemperatura = new javax.swing.JLabel();
    private final javax.swing.JLabel lblUmidade = new javax.swing.JLabel();
    private final javax.swing.JLabel lblUmidificador = new javax.swing.JLabel();
    private javax.swing.JLabel lblVentilador;
    private final javax.swing.JPanel pnlAtuadorLuminosidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlAtuadorUmidade = new javax.swing.JPanel();
    private javax.swing.JPanel pnlAtuadoresTemperatura;
    private final javax.swing.JPanel pnlControleLuminosidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlControleTemperatura = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlControleUmidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlSensorLuminosidade = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlSensorTemperatura = new javax.swing.JPanel();
    private final javax.swing.JPanel pnlSensorUmidade = new javax.swing.JPanel();
    private final javax.swing.JToggleButton tbtnIniciarSimulacao = new javax.swing.JToggleButton();
    private final javax.swing.JToggleButton tbtnInterruptorAquecedor = new javax.swing.JToggleButton();
    private final javax.swing.JToggleButton tbtnInterruptorLampada = new javax.swing.JToggleButton();
    private final javax.swing.JToggleButton tbtnInterruptorUmidificador = new javax.swing.JToggleButton();
    private final javax.swing.JToggleButton tbtnInterruptorVentilador = new javax.swing.JToggleButton();
    // End of variables declaration//GEN-END:variables
}
