.PHONY: clean All

All:
	@echo "----------Building project:[ IntegrateSysLib - Release ]----------"
	@$(MAKE) -f  "IntegrateSysLib.mk"
clean:
	@echo "----------Cleaning project:[ IntegrateSysLib - Release ]----------"
	@$(MAKE) -f  "IntegrateSysLib.mk" clean
